### ISSUE TITLE
Maybe don't have to use a headless browser

### ISSUE THREAD

**Issue by ifvv** [atlonxp/recursive-goIndex-downloader#1]
Today I want to download all the files from goindex. This project is exactly what I am looking for. Your work is very good.
However, I noticed that you used a headless browser, which tends to reduce efficiency and increase memory usage usually.
Although goindex requires browsers to parse javascript, it is not necessary to use it.
I noticed that if you send a post request to goindex directly, it will return everything we need.
For example:
` curl 'https://index.gd.workers.dev/' -d ''`
It returns:
```
{"files":[{"id":"1xe7jgnK-7578LORr-ukQgp_ktME_Z_o1","name":"4K北京烤鸭与美女","mimeType":"application/vnd.google-apps.folder","modifiedTime":"2019-06-21T19:20:45.091Z"},{"id":"1iIk47EONL7GWdGr555B7mymbY-qB5fMZ","name":"test","mimeType":"application/vnd.google-apps.folder","modifiedTime":"2018-08-03T12:18:33.839Z"},{"id":"1V8qDc8NfhhwT6f96FtVrWhUYw4B0VKDD","name":"无标题&文件夹","mimeType":"application/vnd.google-apps.folder","modifiedTime":"2019-09-08T13:07:13.037Z"},{"id":"1y9YiRBwUO1kqzM4cLqBNqZwCNM0yn2xl","name":"12'3.txt","mimeType":"text/plain","modifiedTime":"2019-09-12T01:12:05.442Z","size":"6"},{"id":"1egQFJOv-xFhNdTQNciLfcjbwt9li7mz-","name":"HEAD.md","mimeType":"text/markdown","modifiedTime":"2019-09-08T14:45:11.673Z","size":"47"},{"id":"1VJxEj6qCEVnXUxkdtILuSHxE71FEjqwV","name":"README.md","mimeType":"text/markdown","modifiedTime":"2019-09-08T14:46:04.556Z","size":"1348"},{"id":"1cqVl2wSGx92UTdhOxU9pW3wJgmvZMT_J","name":"win8.1emb_x64.tar.gz","mimeType":"application/x-gzip","modifiedTime":"2019-09-06T04:23:47.356Z","size":"3078650423"}]}
```
This is only my personal suggestions.I hope it can help simplify the code.
Have a nice day.

**Comment by atlonxp** [comment]
post request seems interesting to me, I will have a look

**Comment by atlonxp** [comment]
version 2 added

**Comment by ifvv** [comment]
Thanks a lot. I also tried to code a moment ago..But I got stuck in a pile of bugs.. :P
