### ISSUE TITLE
Errors while running cell5 In V2

### ISSUE THREAD

**Issue by JohnDavid07** [atlonxp/recursive-goIndex-downloader#10]
![err](https://user-images.githubusercontent.com/61653507/88690725-91e03900-d119-11ea-983d-f2df0a331f13.png)

**Comment by JohnDavid07** [comment]
`exclusions = ['__MACOSX/']

destination = "/content/drive/My Drive/"
download_tasks = [
    {
        'folder': 'gdppci',
        'url': 'https://text.csalgo1.workers.dev/0:/Grokking%20Dynamic%20Programming%20Patterns%20for%20Coding%20Interviews/'
    },
]

print('##################################')
print('# Crawling all downloadable urls #')
print('##################################', end='\n\n')
tasks = []
for task in download_tasks:
    tasks += crawler_v2(task['url'], [], os.path.join(destination, task['folder']), 0, exclusions, verbose=False)
    # print(json.dumps(tasks, indent=2), end='\n\n')

total_size = get_filesize(sum([int(task['size']) for task in tasks]))

# print(json.dumps(tasks, indent=2))
print('\nTotal Task:', len(tasks))
print('Total size: %.3fGB' % total_size, end='\n\n')`

**Comment by JohnDavid07** [comment]
`exclusions = ['__MACOSX/']

destination = "/content/drive/My Drive/"
download_tasks = [
    {
        'folder': 'gdppci',
        'url': 'https://........................workers.dev/0:/..................................'  (something private url)
    },
]

print('##################################')
print('# Crawling all downloadable urls #')
print('##################################', end='\n\n')
tasks = []
for task in download_tasks:
    tasks += crawler_v2(task['url'], [], os.path.join(destination, task['folder']), 0, exclusions, verbose=False)
    # print(json.dumps(tasks, indent=2), end='\n\n')

total_size = get_filesize(sum([int(task['size']) for task in tasks]))

# print(json.dumps(tasks, indent=2))
print('\nTotal Task:', len(tasks))
print('Total size: %.3fGB' % total_size, end='\n\n')`

**Comment by JohnDavid07** [comment]
``exclusions = ['__MACOSX/']

destination = "/content/drive/My Drive/"
download_tasks = [
{
'folder': 'gdppci',
'url': 'https://........................workers.dev/0:/..................................' (something private url)
},
]

print('##################################')
print('# Crawling all downloadable urls #')
print('##################################', end='\n\n')
tasks = []
for task in download_tasks:
tasks += crawler_v2(task['url'], [], os.path.join(destination, task['folder']), 0, exclusions, verbose=False)
## print(json.dumps(tasks, indent=2), end='\n\n')

total_size = get_filesize(sum([int(task['size']) for task in tasks]))

print(json.dumps(tasks, indent=2))
print('\nTotal Task:', len(tasks))
print('Total size: %.3fGB' % total_size, end='\n\n')``

**Comment by JohnDavid07** [comment]
Can you please give/post a guide on how to use.

**Comment by atlonxp** [comment]
Huh! You don't seem to aware that tutflix (aka tutnetflix) has been banned from Cloudflare. The links you provided were not available long ago.

Easy way to check if the link working is to visit the GoIndex website.
- if it displays its contents --> it is working
- if it does not display anything, just loading progress toolbar --> not working at all.
![Screen Shot 2020-08-23 at 5 54 07 PM](https://user-images.githubusercontent.com/38250872/90983928-a6bdba00-e569-11ea-99ab-89e9882c4cda.png)

**Comment by NullBruce** [comment]
@atlonxp here's a link that doesn't work, also i tried with multiple ones that are up.

#################################
# Crawling all downloadable urls #
##################################

https://manga.td-index.workers.dev/0:/
retry #2 https://manga.td-index.workers.dev/0:/
retry #3 https://manga.td-index.workers.dev/0:/
retry #4 https://manga.td-index.workers.dev/0:/
retry #5 https://manga.td-index.workers.dev/0:/
- Data is missing! change a plan -
- > use terminal CURL            -
Nah, something went wrong!

---------------------------------------------------------------------------

JSONDecodeError                           Traceback (most recent call last)

<ipython-input-3-8a535f51cf5f> in crawler_v2(url, downloading_dict, path, level, exclusions, verbose)
     55             response = os.popen("curl --globoff {} -d ''".format(url.geturl())).read()
---> 56             response_json = json.loads(response)
     57         except Exception as e:

4 frames

JSONDecodeError: Expecting value: line 1 column 1 (char 0)


During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)

<ipython-input-3-8a535f51cf5f> in crawler_v2(url, downloading_dict, path, level, exclusions, verbose)
     57         except Exception as e:
     58             print('Nah, something went wrong!')
---> 59             print(e.args())
     60             return []
     61     except Exception as e:

TypeError: 'tuple' object is not callable

**Comment by Rudo2204** [comment]
@NullBruce Acrous index is not yet supported. See #7 
I tried to poke around a bit but nothing seems to work :(

**Comment by atlonxp** [comment]
@Rudo2204 @NullBruce i need to have a look around how Acrous working. I think it is just a theme but there might as well be some script for a dynamic content generation (which is causing the problem)
